name: Publish to NPM and update documentation

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build
        run: |
          npm ci
          npm run build-all
      - name: Publish NPM Module
        uses: JS-DevTools/npm-publish@v1
        with:
          check-version: false
          token: ${{ secrets.NPM_TOKEN }}
      # Only build and publish documentation once we've successfully published to NPM
      - name: Build documentation
        run: npm run build-docs
      # This will make documentation available at
      # https://<username>.github.io/canvas-datagrid/docs/
      - name: Publish documentation to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
